# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8c06c1772b384c7173ae092a5da9fad3"
name = "Shop-MCP"
application_url = "https://shop-mcp-23.onrender.com"
embedded = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_metaobjects,read_metaobjects,write_metaobject_definitions,read_metaobject_definitions,read_publications,write_publications"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://shop-mcp-23.onrender.com/auth/callback", "https://shop-mcp-23.onrender.com/auth/shopify/callback", "https://shop-mcp-23.onrender.com/api/auth/callback" ]
[build]
automatically_update_urls_on_dev = true
